### ISSUE TITLE
Problem with Nebula 4.12?

### ISSUE THREAD

**Issue by kzapolski** [OpenNebula/addon-knife#5]
# knife opennebula template list -VV
INFO: Using configuration from /root/.chef/knife.rb
/opt/chefdk/embedded/apps/chef/lib/chef/client.rb:160:in `delete': no implicit conversion of Symbol into String (TypeError)
	from /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:160:in `initialize'
	from /root/.chefdk/gem/ruby/2.1.0/gems/knife-opennebula-0.1.0/lib/chef/knife/opennebula_base.rb:55:in `new'
	from /root/.chefdk/gem/ruby/2.1.0/gems/knife-opennebula-0.1.0/lib/chef/knife/opennebula_base.rb:55:in `client'
	from /root/.chefdk/gem/ruby/2.1.0/gems/knife-opennebula-0.1.0/lib/chef/knife/opennebula_template_list.rb:25:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:417:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:416:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:213:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:40:in `load'
	from /opt/chefdk/bin/knife:40:in `<main>'

**Comment by thomasalrin** [comment]
Hi Karol Zapolski, 
  We have clear the fix in knife-opennebula v 0.2.0. Just try it. Actually now we use 'fog' gem.
